name: CI/CD Pipeline

on:
  push:
    branches: [ master, main, dev, v1.x, ci ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master, main ]

env:
  BUILD_TYPE: Release

jobs:
  # ================================ Code Quality Checks ================================
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Configure environment and install tools
      run: |
        echo "=== Running environment configuration script ==="
        python3 scripts/configure.py --platform=linux --code-quality
        
        echo "=== Verifying code quality tools ==="
        clang-format --version || echo "clang-format not found"
        cppcheck --version || echo "cppcheck not found"
        cpplint --version || echo "cpplint not found"

    - name: Run code quality checks
      run: |
        echo "=== Running cppcheck static analysis ==="
        cppcheck --enable=all --std=c++17 --suppress=missingIncludeSystem \
          --error-exitcode=1 --xml libcpp/ 2> cppcheck-result.xml || true
        
        echo "=== Running clang-format check ==="
        find libcpp -name "*.cpp" -o -name "*.hpp" -o -name "*.h" | \
        xargs clang-format --style=file --dry-run --Werror
        
        echo "=== Running cpplint check ==="
        find libcpp -name "*.cpp" -o -name "*.hpp" -o -name "*.h" | \
        xargs cpplint --filter=-build/c++11,-whitespace/braces || true

    - name: Upload code quality reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: code-quality-reports
        path: |
          cppcheck-result.xml
        retention-days: 30

  # ================================ Build (Linux) ================================
  build-linux:
    name: Build and Test (Linux)
    runs-on: ubuntu-22.04
    needs: code-quality
    strategy:
      matrix:
        build_type: [Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Setup virtual display
      run: |
        export DISPLAY=:99.0
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo "DISPLAY=:99.0" >> $GITHUB_ENV

    - name: Configure build environment
      run: |
        echo "=== Running environment configuration script ==="

        # wait for any dpkg locks to clear
        while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 1; done
        python3 scripts/configure.py --platform=linux
        
        # Source environment variables for current session
        if [ -f ~/.bashrc ]; then
          source ~/.bashrc
        fi

        bash scripts/dpdk.sh

        # Source environment variables for current session
        if [ -f ~/.bashrc ]; then
          source ~/.bashrc
        fi

        echo "=== Verifying environment setup ==="
        
        # Verify tools are available
        echo "Tool verification:"
        echo "  CMake: $(cmake --version | head -1)"
        echo "  Ninja: $(ninja --version)"
        echo "  GCC: $(gcc --version | head -1)"
        echo "  G++: $(g++ --version | head -1)"
        
        # Check vcpkg
        if [ -d "tools/vcpkg" ]; then
          echo "  vcpkg: $(./tools/vcpkg/vcpkg version | head -1)"
          echo "VCPKG_ROOT=${{ github.workspace }}/tools/vcpkg" >> $GITHUB_ENV
          echo "${{ github.workspace }}/tools/vcpkg" >> $GITHUB_PATH
        fi
        
        # Configure vcpkg binary caching
        export VCPKG_BINARY_SOURCES="clear;x-gha,readwrite"
        echo "VCPKG_BINARY_SOURCES=clear;x-gha,readwrite" >> $GITHUB_ENV

    - name: Configure CMake
      env:
        CMAKE_MAKE_PROGRAM: ninja
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
      run: |
        echo "=== Pre-configure disk usage ==="
        df -h
        echo "================================="
        
        echo "=== Running CMake configuration ==="
        
        cmake -B build \
          -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DBUILD_TEST=ON \
          -DBUILD_LIB=OFF \
          -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
          -DASAN=${{ matrix.build_type == 'Debug' && 'ON' || 'OFF' }} \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        
        echo "=== Post-configure disk usage ==="
        df -h
        echo "=================================="

    - name: Build
      run: |
        echo "=== Pre-build disk usage ==="
        df -h
        echo "============================="
        
        cmake --build build --config ${{ matrix.build_type }} --parallel $(nproc)
        
        echo "=== Post-build disk usage ==="
        df -h
        echo "=============================="

    - name: Run tests
      working-directory: build
      run: |
        ctest --output-on-failure --parallel $(nproc) -C ${{ matrix.build_type }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-logs-linux-${{ matrix.build_type }}
        path: |
          build/CMakeFiles/CMakeOutput.log
          build/CMakeFiles/CMakeError.log
          build/compile_commands.json
          build/vcpkg-manifest-install.log
        retention-days: 7

  # ================================ Build (macOS) ================================
  build-macos:
    name: Build and Test (macOS)
    runs-on: macos-13
    needs: code-quality
    strategy:
      matrix:
        build_type: [Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check system info
      run: |
        echo "=== System Information ==="
        uname -a
        sysctl hw.model
        sysctl machdep.cpu.brand_string 2>/dev/null || echo "CPU info not available"
        echo "=== Initial disk usage ==="
        df -h
        echo "=========================="

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Configure build environment (macOS)
      run: |
        echo "=== Setting up macOS build environment ==="
        
        # Set environment variables for macOS
        echo "Setting macOS deployment target..."
        echo "MACOSX_DEPLOYMENT_TARGET=10.15" >> $GITHUB_ENV
        export MACOSX_DEPLOYMENT_TARGET=10.15
        
        # Install required packages including autoconf-archive
        echo "=== Installing required packages ==="
        brew install automake autoconf-archive || true
        brew unlink automake autoconf 2>/dev/null || true
        brew link --force --overwrite automake autoconf autoconf-archive || true
        
        # Find and fix aclocal - multiple strategies
        echo "=== Finding and fixing aclocal ==="
        
        # Strategy 1: Direct symlink from opt to bin
        if [ -f "/usr/local/opt/automake/bin/aclocal" ] && [ ! -f "/usr/local/bin/aclocal" ]; then
          sudo ln -sf /usr/local/opt/automake/bin/aclocal /usr/local/bin/aclocal
          echo "✓ Created symlink: /usr/local/bin/aclocal -> /usr/local/opt/automake/bin/aclocal"
        fi
        
        # Strategy 2: Find in Cellar and link
        if [ ! -f "/usr/local/bin/aclocal" ]; then
          ACLOCAL_PATH=$(find /usr/local/Cellar/automake*/bin -name aclocal 2>/dev/null | head -1)
          if [ -n "$ACLOCAL_PATH" ] && [ -f "$ACLOCAL_PATH" ]; then
            sudo ln -sf "$ACLOCAL_PATH" /usr/local/bin/aclocal
            echo "✓ Created symlink from Cellar: /usr/local/bin/aclocal -> $ACLOCAL_PATH"
          fi
        fi
        
        # Strategy 3: Copy instead of symlink if symlink fails
        if [ ! -f "/usr/local/bin/aclocal" ]; then
          for ACLOCAL_SOURCE in "/usr/local/opt/automake/bin/aclocal" $(find /usr/local/Cellar/automake*/bin -name aclocal 2>/dev/null); do
            if [ -f "$ACLOCAL_SOURCE" ]; then
              sudo cp "$ACLOCAL_SOURCE" /usr/local/bin/aclocal
              sudo chmod +x /usr/local/bin/aclocal
              echo "✓ Copied aclocal: $ACLOCAL_SOURCE -> /usr/local/bin/aclocal"
              break
            fi
          done
        fi
        
        # Strategy 4: Add automake bin directory to PATH
        export PATH="/usr/local/opt/automake/bin:$PATH"
        echo "PATH=/usr/local/opt/automake/bin:$PATH" >> $GITHUB_ENV
        
        # Strategy 5: Set ACLOCAL environment variable directly
        if [ -f "/usr/local/opt/automake/bin/aclocal" ]; then
          echo "ACLOCAL=/usr/local/opt/automake/bin/aclocal" >> $GITHUB_ENV
          export ACLOCAL="/usr/local/opt/automake/bin/aclocal"
        fi
        
        # Verify aclocal is now accessible
        echo "=== Verifying aclocal ==="
        if command -v aclocal >/dev/null 2>&1; then
          echo "✓ aclocal found at: $(which aclocal)"
          aclocal --version | head -1 || echo "aclocal version check failed"
        else
          echo "✗ aclocal still not found in PATH"
          echo "Listing automake installation:"
          ls -la /usr/local/opt/automake/bin/ 2>/dev/null || echo "automake opt dir not found"
          ls -la /usr/local/Cellar/automake*/bin/ 2>/dev/null || echo "automake cellar dir not found"
        fi
        
        # Also fix other autotools
        echo "=== Fixing other autotools ==="
        for tool in autoconf autoheader autom4te autoreconf libtool libtoolize m4; do
          if [ ! -f "/usr/local/bin/$tool" ]; then
            # Try to find in opt
            if [ -f "/usr/local/opt/autoconf/bin/$tool" ]; then
              sudo ln -sf "/usr/local/opt/autoconf/bin/$tool" "/usr/local/bin/$tool" 2>/dev/null || true
            elif [ -f "/usr/local/opt/libtool/bin/$tool" ]; then
              sudo ln -sf "/usr/local/opt/libtool/bin/$tool" "/usr/local/bin/$tool" 2>/dev/null || true
            elif [ -f "/usr/local/opt/m4/bin/$tool" ]; then
              sudo ln -sf "/usr/local/opt/m4/bin/$tool" "/usr/local/bin/$tool" 2>/dev/null || true
            fi
          fi
        done
        
        # Verify autoconf-archive is available
        echo "=== Verifying autoconf-archive ==="
        if brew list autoconf-archive >/dev/null 2>&1; then
          echo "✓ autoconf-archive is installed"
          
          # Make sure autoconf-archive macros are available to aclocal
          AUTOCONF_ARCHIVE_DIR="/usr/local/share/aclocal"
          if [ -d "$AUTOCONF_ARCHIVE_DIR" ]; then
            echo "✓ autoconf-archive macros found at: $AUTOCONF_ARCHIVE_DIR"
          else
            echo "✗ autoconf-archive macros not found"
          fi
        else
          echo "✗ autoconf-archive not installed"
        fi
        
        # Run environment configuration script
        echo "=== Running environment configuration script ==="
        python3 scripts/configure.py --platform=macos

        bash scripts/dpdk.sh
        
        echo "=== Verifying environment setup ==="
        # Set up critical autotools paths explicitly
        export PATH="/usr/local/bin:/usr/local/opt/autoconf/bin:/usr/local/opt/automake/bin:/usr/local/opt/libtool/bin:/usr/local/opt/m4/bin:/usr/local/opt/gettext/bin:$PATH"
        export ACLOCAL_PATH="/usr/local/share/aclocal:/usr/local/opt/autoconf/share/aclocal:/usr/local/opt/automake/share/aclocal:/usr/local/opt/libtool/share/aclocal:/usr/local/opt/gettext/share/aclocal"
        
        # Add to GitHub ENV for later steps
        echo "PATH=$PATH" >> $GITHUB_ENV
        echo "ACLOCAL_PATH=$ACLOCAL_PATH" >> $GITHUB_ENV
        
        # Final verification of critical autotools
        echo "=== Final autotools verification ==="
        for tool in autoconf automake aclocal autoreconf libtool m4; do
          if command -v $tool >/dev/null 2>&1; then
            echo "✓ $tool: $(which $tool)"
          else
            echo "✗ $tool: not found"
          fi
        done
        
        # Test autoreconf specifically (this is what fails)
        echo "=== Testing autoreconf ==="
        if command -v autoreconf >/dev/null 2>&1; then
          echo "✓ autoreconf found at: $(which autoreconf)"
          # Test in a temporary directory
          mkdir -p /tmp/autotools_test
          cd /tmp/autotools_test
          echo "AC_INIT([test], [1.0])" > configure.ac
          echo "AC_OUTPUT" >> configure.ac
          autoreconf -i 2>/dev/null && echo "✓ autoreconf test passed" || echo "✗ autoreconf test failed"
          cd - >/dev/null
          rm -rf /tmp/autotools_test
        else
          echo "✗ autoreconf not found"
        fi
        
        # Set compiler environment variables
        echo "CC=$(which clang)" >> $GITHUB_ENV
        echo "CXX=$(which clang++)" >> $GITHUB_ENV
        
        # Verify tools are available
        echo "Tool verification:"
        echo "  CMake: $(cmake --version | head -1)"
        echo "  Ninja: $(ninja --version)"
        echo "  Clang: $(clang --version | head -1)"
        echo "  Clang++: $(clang++ --version | head -1)"
        
        # Check vcpkg
        if [ -d "tools/vcpkg" ]; then
          echo "  vcpkg: $(./tools/vcpkg/vcpkg version | head -1)"
          echo "VCPKG_ROOT=${{ github.workspace }}/tools/vcpkg" >> $GITHUB_ENV
          echo "${{ github.workspace }}/tools/vcpkg" >> $GITHUB_PATH
        fi
        
        # Configure vcpkg binary caching
        export VCPKG_BINARY_SOURCES="clear;x-gha,readwrite"
        echo "VCPKG_BINARY_SOURCES=clear;x-gha,readwrite" >> $GITHUB_ENV

    - name: Create vcpkg triplet for macOS
      run: |
        echo "=== Creating custom vcpkg triplet ==="
        mkdir -p tools/vcpkg/triplets/community
        
        # Create a custom triplet with relaxed compiler settings
        cat > tools/vcpkg/triplets/community/x64-osx-relaxed.cmake << 'EOF'
        set(VCPKG_TARGET_ARCHITECTURE x64)
        set(VCPKG_CRT_LINKAGE dynamic)
        set(VCPKG_LIBRARY_LINKAGE static)
        set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
        set(VCPKG_OSX_DEPLOYMENT_TARGET "10.15")
        
        # Relax compiler warnings for boost
        set(VCPKG_CXX_FLAGS "-Wno-deprecated -Wno-deprecated-declarations -Wno-enum-constexpr-conversion -Wno-deprecated-builtins")
        set(VCPKG_C_FLAGS "-Wno-deprecated -Wno-deprecated-declarations")
        EOF
        
        echo "Custom triplet created:"
        cat tools/vcpkg/triplets/community/x64-osx-relaxed.cmake

    - name: Configure CMake (macOS)
      env:
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
        MACOSX_DEPLOYMENT_TARGET: "10.15"
        ACLOCAL: "/usr/local/bin/aclocal"
        AUTOMAKE: "/usr/local/bin/automake"
        AUTORECONF: "/usr/local/bin/autoreconf"
        LIBTOOL: "/usr/local/bin/libtool"
        M4: "/usr/local/bin/m4"
      run: |
        echo "=== Pre-configure disk usage ==="
        df -h
        echo "================================="
        
        echo "=== Environment Variables ==="
        echo "CC: $CC"
        echo "CXX: $CXX"
        echo "MACOSX_DEPLOYMENT_TARGET: $MACOSX_DEPLOYMENT_TARGET"
        echo "VCPKG_ROOT: $VCPKG_ROOT"
        echo "ACLOCAL: $ACLOCAL"
        echo "PATH: $PATH"
        echo "ACLOCAL_PATH: $ACLOCAL_PATH"
        echo "=============================="
        
        # check autotools
        echo "=== Final autotools check before CMake ==="
        which aclocal || echo "aclocal not in PATH"
        which autoreconf || echo "autoreconf not in PATH"
        ls -la /usr/local/bin/aclocal 2>/dev/null || echo "aclocal not in /usr/local/bin"
        
        echo "=== Running CMake configuration ==="
        
        cmake -B build \
          -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DBUILD_TEST=ON \
          -DBUILD_LIB=OFF \
          -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
          -DASAN=OFF \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
          -DCMAKE_C_COMPILER=$CC \
          -DCMAKE_CXX_COMPILER=$CXX \
          -DCMAKE_MAKE_PROGRAM=$(which ninja) \
          -DVCPKG_TARGET_TRIPLET=x64-osx-relaxed \
          -DCMAKE_CXX_FLAGS="-Wno-deprecated -Wno-deprecated-declarations -Wno-enum-constexpr-conversion -Wno-deprecated-builtins" \
          -DCMAKE_C_FLAGS="-Wno-deprecated -Wno-deprecated-declarations"
        
        echo "=== Post-configure disk usage ==="
        df -h
        echo "=================================="

    - name: Build (macOS)
      run: |
        echo "=== Pre-build disk usage ==="
        df -h
        echo "============================="
        
        # Set number of parallel jobs (use fewer cores on macOS to avoid memory issues)
        NPROC=$(sysctl -n hw.ncpu)
        PARALLEL_JOBS=$((NPROC > 4 ? 4 : NPROC))
        echo "Using $PARALLEL_JOBS parallel jobs (total cores: $NPROC)"
        
        cmake --build build --config ${{ matrix.build_type }} --parallel $PARALLEL_JOBS
        
        echo "=== Post-build disk usage ==="
        df -h
        echo "=============================="

    - name: Run tests (macOS)
      working-directory: build
      run: |
        # Use fewer parallel jobs for testing to avoid resource conflicts
        NPROC=$(sysctl -n hw.ncpu)
        PARALLEL_JOBS=$((NPROC > 2 ? 2 : NPROC))
        echo "Running tests with $PARALLEL_JOBS parallel jobs"
        
        ctest --output-on-failure --parallel $PARALLEL_JOBS -C ${{ matrix.build_type }}

    - name: Upload build artifacts (macOS)
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-logs-macos-${{ matrix.build_type }}
        path: |
          build/CMakeFiles/CMakeOutput.log
          build/CMakeFiles/CMakeError.log
          build/compile_commands.json
          build/vcpkg-manifest-install.log
          tools/vcpkg/buildtrees/boost-thread/install-*-out.log
          tools/vcpkg/triplets/community/x64-osx-relaxed.cmake
        retention-days: 7

  # ================================ Build Summary ================================
  build-summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos]
    if: always()
    
    steps:
    - name: Check build results
      run: |
        echo "=== Build Summary ==="
        echo "Linux build: ${{ needs.build-linux.result }}"
        echo "macOS build: ${{ needs.build-macos.result }}"
        echo "===================="
        
        # Set overall status
        success_count=0
        total_count=2
        
        if [[ "${{ needs.build-linux.result }}" == "success" ]]; then
          success_count=$((success_count + 1))
        fi
        
        if [[ "${{ needs.build-macos.result }}" == "success" ]]; then
          success_count=$((success_count + 1))
        fi
        
        echo "Successful builds: $success_count/$total_count"
        
        if [[ $success_count -eq $total_count ]]; then
          echo "All builds passed!"
          exit 0
        elif [[ $success_count -eq 0 ]]; then
          echo "All builds failed!"
          exit 1
        else
          echo "Some builds failed!"
          exit 1
        fi